### ISSUE TITLE
colcon build error on Windows x64 for python_orocos_kdl

### ISSUE THREAD

**Issue by felixf4xu** [ros2/orocos_kdl_vendor#24]
in `C:\ros\rolling>` I run:
```
colcon build --merge-install  --event-handlers console_direct+ \
  --cmake-args -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  -DCMAKE_PREFIX_PATH="C:\Program Files\Boost\lib\cmake" -DBUILD_TESTING=OFF \
  --no-warn-unused-cli --cmake-clean-cache --packages-select python_orocos_kdl
```

then I have this error:
```
--- stderr: python_orocos_kdl
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\colcon_core\executor\__init__.py", line 91, in __call__
    rc = await self.task(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\colcon_core\task\__init__.py", line 93, in __call__
    return await task_method(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\colcon_ros\task\catkin\build.py", line 75, in build
    rc = await extension.build(
  File "C:\Program Files\Python310\lib\site-packages\colcon_cmake\task\cmake\build.py", line 103, in build
    rc = await self._build(
  File "C:\Program Files\Python310\lib\site-packages\colcon_cmake\task\cmake\build.py", line 236, in _build
    if not await has_target(args.build_base, target):
  File "C:\Program Files\Python310\lib\site-packages\colcon_cmake\task\cmake\__init__.py", line 63, in has_target
    assert target == 'install'
AssertionError
```
I'm not sure if it's related to `colcon_cmake`. If I use colcon to build ros2 (rolling), I can successful build the whole other ros2 source.

I don't know where should I start to debug.

in my `C:\Program Files\Python310\lib\site-packages\colcon_cmake\task\cmake\__init__.py`:

```
async def has_target(path, target):
    """
    Check if the CMake generated build system has a specific target.

    :param str path: The path of the directory contain the generated build
      system
    :param str target: The name of the target
    :rtype: bool
    """
    generator = get_generator(path)
    if 'Unix Makefiles' in generator:
        return target in await get_makefile_targets(path)
    if 'Ninja' in generator:
        return target in get_ninja_targets(path)
    if 'Visual Studio' in generator:
        print(path)
        print(target)
        assert target == 'install'
        install_project_file = get_project_file(path, 'INSTALL')
        return install_project_file is not None
    assert False, \
        "'has_target' not implemented for CMake generator '{generator}'" \
        .format_map(locals())
```
maybe it's why it happens only in windows (visual studio): `if 'Visual Studio' in generator`.

**Comment by felixf4xu** [comment]
it seems that it open happens in `Release` build:

if I use `-DCMAKE_BUILD_TYPE=Release`, I have the exact error as above.

But If I use `-DCMAKE_BUILD_TYPE=Debug`, the error above does not show up (it show some other link error)

**Comment by felixf4xu** [comment]
I'm sorry, I posted here wrong. It should be for https://github.com/orocos/orocos_kinematics_dynamics
